groupsUrl:
#  - https://raw.githubusercontent.com/arcolinuxiso/carli-calamares-config/master/etc/calamares/modules/netinstall-example.yaml
#  - file:///etc/calamares/modules/netinstall-software.yaml
   - file:///usr/share/astroarch_onboarding/configs/netinstall_software.yaml





required: false

label:
    sidebar: "Software"
    sidebar[fr]: "Logiciels"
    sidebar[ja]: "例"
    title: "Software"
    title[fr]: "Logiciels"
    title[ja]: "例"
